### ISSUE TITLE
Suggestion: Production less expensive

### ISSUE THREAD

**Issue by FalcoGer** [ufoaiorg/ufoai#55]
Currently production of items costs just as much as buying them. For things you can't buy anyway, this makes no difference. For anything else it makes no sense to produce those items, unless you somehow buy out the stock of 100 units.
I propose that manufacturing items should be a fraction of the cost of buying them, because you already pay more because you need to pay the workers. Of course this needs a look into balancing so that you can't churn out expensive, but quick to produce items which you can then sell for silly profits.

**Comment by vedran-brnjetic** [comment]
From another angle, PHALANX has spent a great deal of expertise and effort to research, develop and produce some of the Earth's best weapon systems, and should be selling those highly demanded exclusive items at _some_ profit, since all other militaries are looking to get them for their own soldiers. Sure enough, the countries that fund PHALANX could have some kind of a sweetheart deal in the contract, but if some country dropped the funding they should be paying more to get those items if they want the best protection the money can buy. :wink: :wink:

**Comment by geever** [comment]
PHALANX's workshops are rather specialized engineering labs than factories, they are not meant to produce profit.

**Comment by FalcoGer** [comment]
What I mean to say is that there is no incentive to produce anything that can be bought because you spend both money and time for workers and workshop space and also pay the full retail price. So producing your own assault rifles would cost more than to buy them.
